### ISSUE TITLE
Design for NavtreeComponent on narrow screen

### ISSUE THREAD

**Issue by Jogo27** [JBoudou/Itero#88]
The NavtreeComponent is this component:
![image](https://user-images.githubusercontent.com/1835665/120162906-2bc0b880-c1f9-11eb-93e1-f815d106997f.png)

It's currently too large on narrow screens:
![image](https://user-images.githubusercontent.com/1835665/120162528-c7055e00-c1f8-11eb-9a50-3aa6a3b417a6.png)

The task of this ticket is to design how this component could look like on narrow screen. The possibility for the component to display more that 3 steps must be taken carefully into account.

**Comment by WanJIN0415** [comment]
#89
